Baikal/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from app import views
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('adminDjango/', admin.site.urls),
    path("main", views.main, name="main"),
    path("main/<str:restaurant_name>", views.restaurantIndex, name="restaurantIndex"),
    path("main/<str:restaurant_name>/reservation", views.restaurantReservation, name="restaurantReservation"),
    path("main/<str:restaurant_name>/menu", views.restaurantMenu, name="restaurantMenu"),
    path('main/<str:restaurant_name>/', include('cart.urls')),

    path("main/<str:restaurant_name>/reviews", views.restaurantReviews, name="restaurantReviews"),
    path("main/<str:restaurant_name>/reviews/add", views.restaurantReviewsAdd, name="restaurantReviewsAdd"),

    path("main/<str:restaurant_name>/orders", views.restaurantOrders, name="restaurantOrders"),
    path("main/<str:restaurant_name>/orders/<int:order_id>", views.restaurantOrderItem, name="restaurantOrderItem"),

    path("profile", views.profile, name="profile"),
    path("login", views.login, name="login"),
    path('logout/', views.logout, name='logout'),
    path("register", views.register, name="register"),

    path("main/<str:restaurant_name>/admin/menu", views.restaurantAdminMenu, name="restaurantAdminMenu"),
    path("main/<str:restaurant_name>/admin/menu/add", views.restaurantAdminMenuAdd, name="restaurantAdminMenuAdd"),
    path("main/<str:restaurant_name>/admin/menu/delete/<int:dish_id>", views.restaurantAdminMenuDelete, name="restaurantAdminMenuDelete"),
    path("main/<str:restaurant_name>/admin/menu/<int:dish_id>", views.restaurantAdminMenuEdit, name="restaurantAdminMenuEdit"),

    path("main/<str:restaurant_name>/admin/orders", views.restaurantAdminOrders, name="restaurantAdminOrders"),
    path("main/<str:restaurant_name>/admin/orders/<int:order_id>", views.restaurantAdminOrderItem, name="restaurantAdminOrderItem"),

    path("main/<str:restaurant_name>/admin/reviews", views.restaurantAdminReviews, name="restaurantAdminReviews"),

    path("main/<str:restaurant_name>/admin/staff", views.restaurantAdminStaff, name="restaurantAdminStaff"),
    path("main/<str:restaurant_name>/admin/staff/add", views.restaurantAdminStaffAdd, name="restaurantAdminStaffAdd"),
    path("main/<str:restaurant_name>/admin/staff/delete/<int:worker_id>", views.restaurantAdminStaffDelete, name="restaurantAdminStaffDelete"),
    path("main/<str:restaurant_name>/admin/staff/<int:worker_id>", views.restaurantAdminStaffEdit, name="restaurantAdminStaffEdit"),

    path("main/<str:restaurant_name>/admin/reservations", views.restaurantAdminReservations, name="restaurantAdminReservations"),
    path("main/<str:restaurant_name>/admin/reservations/add", views.restaurantAdminReservationsAdd, name="restaurantAdminReservationsAdd"),
    path("main/<str:restaurant_name>/admin/reservations/delete/<int:reservation_id>", views.restaurantAdminReservationsDelete, name="restaurantAdminReservationsDelete"),
    path("main/<str:restaurant_name>/admin/reservations/<int:reservation_id>", views.restaurantAdminReservationsEdit, name="restaurantAdminReservationsEdit"),

    path("main/<str:restaurant_name>/admin/profit", views.restaurantAdminProfit, name="restaurantAdminProfit"),

    path("main/<str:restaurant_name>/admin/supplies", views.restaurantAdminSupplies, name="restaurantAdminSupplies"),
    path("main/<str:restaurant_name>/admin/supplies/add", views.restaurantAdminSuppliesAdd, name="restaurantAdminSuppliesAdd"),
    path("main/<str:restaurant_name>/admin/supplies/delete/<int:supply_id>", views.restaurantAdminSuppliesDelete, name="restaurantAdminSuppliesDelete"),
    path("main/<str:restaurant_name>/admin/supplies/<int:supply_id>", views.restaurantAdminSuppliesEdit, name="restaurantAdminSuppliesEdit"),

    path("admin", views.restaurantAdmin, name="restaurantAdmin"),
    path("main/<str:restaurant_name>/admin", views.restaurantAdminEdit, name="restaurantAdminEdit"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from cart import views
from django.conf.urls.static import static

urlpatterns = [
    path("cart", views.cartSummary, name="cartSummary"),
    path("cart/add", views.cartAdd, name="cartAdd"),
    path("cart/delete", views.cartDelete, name="cartDelete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count, Sum, F, Min, Max
from datetime import date, timedelta, time
from django.utils import timezone
from calendar import monthrange
from django.core.validators import RegexValidator

# Create your models here.

class ReviewManager(models.Manager):

    def get_all_by_restaurant(self, restaurant):
        return self.filter(restaurant__name=restaurant)
    
    def get_new_by_restaurant(self, restaurant):
        return self.filter(restaurant__name=restaurant).order_by('-date')[:15]
    
class RestaurantManager(models.Manager):

    def get_by_name(self, _name):
        return self.filter(name = _name)
    

class ReservationManager(models.Manager):

    def get_all_by_restaurant(self, restaurant):
        return self.filter(restaurant__name=restaurant)

    def get_sum_guests_by_restaurant(self, restaurant):
        return self.filter(restaurant__name=restaurant).aggregate(total=Sum("guests", default=0))['total']
       
    
class OrderManager(models.Manager):

    def get_all_by_restaurant(self, restaurant):
        return self.filter(restaurant__name=restaurant)
    
    def get_new_by_restaurant(self, restaurant):
        return self.filter(restaurant__name=restaurant).order_by('-date')[:15]
    
    def get_all_by_user_and_restaurant(self, user, restaurant):
        return self.filter(profile__user = user).filter(restaurant__name=restaurant).order_by('-date')
    
    def get_sum_cost_by_id(self, order_id):
        return self.filter(id=order_id).aggregate(total=Sum(F('dishes__dish__price') * F('dishes__quantity')))['total']
    
    def get_sum_cost_by_restaurant_date(self, restaurant, date):
        return self.filter(restaurant__name=restaurant).filter(date__date=date).aggregate(total=Sum(F('dishes__dish__price') * F('dishes__quantity'), default=0))['total']
    
    def get_sum_guests_by_restaurant_date(self, restaurant, date):
        return self.filter(restaurant__name=restaurant).filter(date__date=date).aggregate(total=Sum("guests", default=0))['total']
    

class DishManager(models.Manager):

    def get_restaurant(self, restaurant):
        return self.filter(section__menu__restaurant__name = restaurant)
    
    def get_popular_dishes(self):
        return self.annotate(num_dish = Count('order')).order_by('-num_dish')[:5]
    
class MenuManager(models.Manager):

    def get_restaurant(self, restaurant):
        return self.filter(restaurant__name = restaurant)
    
class WorkerManager(models.Manager):

    def get_profession(self, _profession):
        return super().get_queryset().filter(profession__name = _profession)

    def get_highly_paid_waiters(self):
        return self.order_by('salary')
    
    def get_sum_cost_by_restaurant(self, restaurant):
        return self.filter(profession__restaurant__name=restaurant).aggregate(total=Sum("salary", default=0))['total']

class SupplyManager(models.Manager):

    def get_all_by_restaurant(self, restaurant):
        return self.filter(restaurant__name=restaurant)
    
    def get_sum_cost_by_restaurant(self, restaurant):
        return self.filter(restaurant__name=restaurant).aggregate(total=Sum(F('price') * F('weight'), default=0))['total']
    
class RevenueManager(models.Manager):

    def get_by_current_month_and_restaurant(self, restaurant):
        return self.filter(restaurant__name=restaurant).filter(date__range=(
            date(date.today().year, date.today().month, 1), 
            date(date.today().year, date.today().month, monthrange(date.today().year, date.today().month)[1])
        ))
    
    def get_sum_profit_by_current_month_and_restaurant(self, restaurant):
        return self.filter(restaurant__name=restaurant).filter(date__range=(
            date(date.today().year, date.today().month, 1), 
            date(date.today().year, date.today().month, monthrange(date.today().year, date.today().month)[1])
        )).aggregate(total=Sum("profit", default=0))['total']

class SectionManager(models.Manager):

    def get_by_name_and_restaurant(self, name, restaurant):
        return self.filter(menu__restaurant__name=restaurant).filter(name=name)

class ProfessionManager(models.Manager):

    def get_by_name_and_restaurant(self, name, restaurant):
        return self.filter(restaurant__name=restaurant).filter(name=name)

class Review(models.Model):
    
    RATING_CHOICES = (
        ('Удивительно!', 'Удивительно!'),
        ('Хорошо!', 'Хорошо!'),
        ('Плохо!', 'Плохо!'),
        ('Ужасно!', 'Ужасно!'),
    )

    title = models.CharField(max_length=50, blank=False)
    content = models.TextField(blank=False, max_length=200)
    date = models.DateTimeField(blank=False, null=True)
    profile = models.ForeignKey('Profile', on_delete=models.PROTECT, blank=True, null=True, default="")
    restaurant = models.ForeignKey('Restaurant', blank=True,  null=True, on_delete=models.PROTECT)
    verdict = models.CharField(choices=RATING_CHOICES, max_length=15, default="")
    
    objects = ReviewManager()

    def __str__(self):
        return f'Review: {self.title}'

class Reservation(models.Model):
    GUESTS_CHOICES = (
        (1, '1 гость'),
        (2, '2 Гостя'),
        (3, '3 Гостя'),
        (4, '4 Гостя'),
        (5, '5 Гостей'),
        (6, '6 Гостей'),
    )
    HOUR_CHOICES = [(time(hour=x), '{:02d}:00'.format(x)) for x in range(10, 23)]

    name = models.CharField(max_length=20, blank=False)
    phone_regex = RegexValidator(regex=r'^\+?[7,8]?[\s,-]?\(?\d{3}\)?[\s,-]?\d{3}[\s,-]?\d{2}[\s,-]?\d{2}$', message="Invalid format")        
    phone = models.CharField(validators=[phone_regex], max_length=12, null=False, blank=False, unique=True)
    guests = models.IntegerField(choices=GUESTS_CHOICES, blank=False, default="")
    date = models.DateField(blank=False, default=timezone.now().date())
    time = models.TimeField(choices=HOUR_CHOICES, blank=False, default="")
    comment = models.TextField(max_length=100, null=True, blank=True)
    restaurant = models.ForeignKey('Restaurant', blank=False,  null=False, on_delete=models.PROTECT, default="")

    objects = ReservationManager()


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.PROTECT, related_name='profile', default="")
    avatar = models.ImageField(null=True, blank=True, default="avatar.png", upload_to="avatar/%Y/%M/%D")

    def __str__(self):
        return f'Profile: {self.user}'
    
    

class Restaurant(models.Model):
    name = models.CharField(blank=False, max_length=32, default="")
    content = models.TextField(blank=False, max_length=200, default="")
    address = models.CharField(blank=False, max_length=50)
    phone_regex = RegexValidator(regex=r'^\+?[7,8]?[\s,-]?\(?\d{3}\)?[\s,-]?\d{3}[\s,-]?\d{2}[\s,-]?\d{2}$', message="Invalid format")        
    phone = models.CharField(validators=[phone_regex], max_length=12, null=True)    
    img = models.ImageField(null=True, blank=True, default="background.jpg", upload_to="restaurant_image/%Y/%M/%D")      

    objects = RestaurantManager()

    def __str__(self):
        return f'{self.name}'

class Order(models.Model):
    profile = models.ForeignKey('Profile', on_delete=models.PROTECT, blank=False, null=True, default="")
    table = models.IntegerField(blank=False, null=True, default=1)
    guests = models.IntegerField(blank=False, null=True, default=1)
    date = models.DateTimeField(blank=False, null=True)
    restaurant = models.ForeignKey('Restaurant', blank=False, on_delete=models.PROTECT)
    objects = OrderManager()

    def __str__(self):
        return f'Order: {self.id}'

class Menu(models.Model):          
    restaurant = models.OneToOneField(
        Restaurant,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    objects = MenuManager()

class Section(models.Model):
    SECTION_CHOICES = (
        ('Комбо', 'Комбо'),
        ('Закуски', 'Закуски'),
        ('Горячее', 'Горячее'),
    )
    menu = models.ForeignKey(
        Menu,
        on_delete=models.CASCADE,
        related_name='sections',
    )
    name = models.CharField(choices=SECTION_CHOICES, max_length=10, blank=False, default="")

    objects = SectionManager()

    def __str__(self):
        return f'{self.name}, {self.menu.restaurant.name}'

class Dish(models.Model):
    name = models.CharField(blank=False, max_length=32)
    content = models.TextField(blank=False, max_length=32)
    section = models.ForeignKey(
        Section,
        on_delete=models.CASCADE,
        related_name='dishes',
        default=""
    )
    price = models.IntegerField()
    weight = models.IntegerField()
    img = models.ImageField(null=True, blank=True, default="dish.webp", upload_to="dish_image/%Y/%M/%D")

    objects = DishManager()


class OrderDish(models.Model):
    dish = models.ForeignKey(Dish, blank=True, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='dishes', null=True)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.dish.name} x{self.quantity}'

class Profession(models.Model):
    PROFESSION_CHOICES = (
        ('Официанты', 'Официанты'),
        ('Повара', 'Повара'),
        ('Менеджеры', 'Менеджеры'),
    )
    restaurant = models.ForeignKey(
        Restaurant,
        on_delete=models.CASCADE,
        related_name='professions',
        default=""
    )
    name = models.CharField(choices=PROFESSION_CHOICES, max_length=10, blank=False, default="")

    objects = ProfessionManager()

    def __str__(self):
        return f'{self.name}, {self.restaurant.name}'

class Worker(models.Model):
    profession = models.ForeignKey(
        Profession,
        on_delete=models.CASCADE,
        related_name='workers',
        default=""
    )
    salary = models.IntegerField()

templates/layouts/restaurant__admin-base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Hunter</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/reset.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/restaurant.css' %}"/>
</head>
<body> 
  <header class="header">
    <a href="{% url 'restaurantIndex' restaurant_name=restaurant.name %}" class="logo">
      {{ restaurant.name }}
    </a>

    <h2 class="nav__title">Добро пожаловать, {{ user.username }}!</h2>

    <div class="icons">
      {% if user.is_authenticated and not request.user.is_superuser %}
      <img class="profile__icon" src="{{ request.user.profile.avatar.url }}" class="fas fa-user profile" id="prof-btn" onclick="toggleMenu()"></img>
      {% else %}
      <img class="profile__icon" src="{% static '/img/avatar.png' %}" class="fas fa-user profile" id="prof-btn" onclick="toggleMenu()"></img>
      {% endif %}
    </div>

    <div class="sub-menu-wrap" id="subMenu">
      <div class="sub-menu">
        <div class="user-info">
          {% if user.is_authenticated and not request.user.is_superuser %} 
          <img src="{{ request.user.profile.avatar.url }}" alt="">
          <h3>{{ user.username }}</h3>
          {% elif request.user.is_superuser  %}
          <img src="{% static '/img/avatar.png' %}" alt="">
          <h3>{{ user.username }}</h3>
          {% else %}
          <img src="{% static '/img/avatar.png' %}" alt="">
          <h3>Anonymus</h3>
          {% endif %}
        </div>
        <hr>
        
        {% if user.is_authenticated %}
        <a href="{% url 'profile' %}" class="sub-menu-link">
          <img src="{% static '/img/setting.png' %}" alt="">
          <p>Edit Profile</p>
          <span>></span>
        </a>
        {% if user.groups.all.0.name == "waiter" or user.groups.all.0.name == "chef" or user.groups.all.0.name == "manager" or request.user.is_superuser %}
        {% if request.user.is_superuser %}
        <a href="{% url 'restaurantAdmin' %}" class="sub-menu-link">
          <img src="{% static '/img/help.png' %}" alt="">
          <p>Admin</p>
          <span>></span>
        </a>
        {% else %}
        <a href="{% url 'restaurantAdminOrders' restaurant_name=request.user.profile.worker.profession.restaurant.name %}" class="sub-menu-link">
          <img src="{% static '/img/help.png' %}" alt="">
          <p>Admin</p>
          <span>></span>
        </a>
        {% endif %}
        {% endif %}
        <a href="{% url 'logout' %}?continue={{ request.get_full_path }}" class="sub-menu-link">
          <img src="{% static '/img/logout.png' %}" alt="">
          <p>Log Out</p>
          <span>></span>
        </a>
        {% else %}
        <a href="{% url 'login' %}?continue={{ request.get_full_path }}" class="sub-menu-link">
          <img src="{% static '/img/setting.png' %}" alt="">
          <p>Login</p>
          <span>></span>
        </a>
        <a href="{% url 'register' %}?continue={{ request.get_full_path }}" class="sub-menu-link">
          <img src="{% static '/img/setting.png' %}" alt="">
          <p>Register</p>
          <span>></span>
        </a>
        {% endif %}

      </div>
    </div>

  </header>

  <section class="main">
    {% block content %}
   
    {% endblock %}
    <div class="main__right">
      {% with request.resolver_match.url_name as url_name %}
      <nav class="main__right__nav">
        {% if request.user.is_superuser %}
        <a class="{% if url_name == 'restaurantAdminEdit' %}current__page{% endif %}" href="{% url 'restaurantAdminEdit' restaurant_name=restaurant.name %}">Ресторан</a>
        {% endif %}
        {% if perms.app.view_worker %}
        <a class="{% if url_name == 'restaurantAdminStaff' %}current__page{% endif %}" href="{% url 'restaurantAdminStaff' restaurant_name=restaurant.name %}">Персонал</a>
        {% endif %}
        {% if perms.app.view_supply %}
        <a class="{% if url_name == 'restaurantAdminSupplies' %}current__page{% endif %}" href="{% url 'restaurantAdminSupplies' restaurant_name=restaurant.name %}">Поставки</a>
        {% endif %}
        {% if perms.app.view_dish %}
        <a class="{% if url_name == 'restaurantAdminMenu' %}current__page{% endif %}" href="{% url 'restaurantAdminMenu' restaurant_name=restaurant.name %}">Меню</a>
        {% endif %}
        {% if perms.app.view_review %}
        <a class="{% if url_name == 'restaurantAdminReviews' %}current__page{% endif %}" href="{% url 'restaurantAdminReviews' restaurant_name=restaurant.name %}">Отзывы</a>
        {% endif %}
        {% if perms.app.view_order %}
        <a class="{% if url_name == 'restaurantAdminOrders' %}current__page{% endif %}" href="{% url 'restaurantAdminOrders' restaurant_name=restaurant.name %}">Заказы</a>
        {% endif %}
        {% if perms.app.view_reservation %}
        <a class="{% if url_name == 'restaurantAdminReservations' %}current__page{% endif %}" href="{% url 'restaurantAdminReservations' restaurant_name=restaurant.name %}">Бронь</a>
        {% endif %}
        {% if perms.app.view_revenue %}
        <a class="{% if url_name == 'restaurantAdminProfit' %}current__page{% endif %}" href="{% url 'restaurantAdminProfit' restaurant_name=restaurant.name %}">Выручка</a>
        {% endif %}
      </nav>   
      {% endwith %} 
    </div>
  </section>


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="{% static 'js/restaurant.js' %}"></script>
  <script src="{% static 'js/edit.js' %}"></script>
</body>
</html>

templates/layouts/restaurant__admin-baseNoLinks.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Hunter</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/reset.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/restaurant.css' %}"/>
</head>
<body> 
  <header class="header">
    <a href="{% url 'main' %}" class="logo">
      BAIKAL
    </a>

    <h2 class="nav__title">Добро пожаловать, {{ user.username }}!</h2>

    <div class="icons">
      {% if user.is_authenticated and not request.user.is_superuser %}
      <img class="profile__icon" src="{{ request.user.profile.avatar.url }}" class="fas fa-user profile" id="prof-btn" onclick="toggleMenu()"></img>
      {% else %}
      <img class="profile__icon" src="{% static '/img/avatar.png' %}" class="fas fa-user profile" id="prof-btn" onclick="toggleMenu()"></img>
      {% endif %}
    </div>

    <div class="sub-menu-wrap" id="subMenu">
      <div class="sub-menu">
        <div class="user-info">
          {% if user.is_authenticated and not request.user.is_superuser %} 
          <img src="{{ request.user.profile.avatar.url }}" alt="">
          <h3>{{ user.username }}</h3>
          {% elif request.user.is_superuser  %}
          <img src="{% static '/img/avatar.png' %}" alt="">
          <h3>{{ user.username }}</h3>
          {% else %}
          <img src="{% static '/img/avatar.png' %}" alt="">
          <h3>Anonymus</h3>
          {% endif %}
        </div>
        <hr>
        
        {% if user.is_authenticated %}
        <a href="{% url 'profile' %}" class="sub-menu-link">
          <img src="{% static '/img/setting.png' %}" alt="">
          <p>Edit Profile</p>
          <span>></span>
        </a>
        {% if user.groups.all.0.name == "waiter" or user.groups.all.0.name == "chef" or user.groups.all.0.name == "manager" or request.user.is_superuser %}
        {% if request.user.is_superuser %}
        <a href="{% url 'restaurantAdmin' %}" class="sub-menu-link">
          <img src="{% static '/img/help.png' %}" alt="">
          <p>Admin</p>
          <span>></span>
        </a>
        {% else %}
        <a href="{% url 'restaurantAdminOrders' restaurant_name=request.user.profile.worker.profession.restaurant.name %}" class="sub-menu-link">
          <img src="{% static '/img/help.png' %}" alt="">
          <p>Admin</p>
          <span>></span>
        </a>
        {% endif %}
        {% endif %}
        <a href="{% url 'logout' %}?continue={{ request.get_full_path }}" class="sub-menu-link">
          <img src="{% static '/img/logout.png' %}" alt="">
          <p>Log Out</p>
          <span>></span>
        </a>
        {% else %}
        <a href="{% url 'login' %}?continue={{ request.get_full_path }}" class="sub-menu-link">
          <img src="{% static '/img/setting.png' %}" alt="">
          <p>Login</p>
          <span>></span>
        </a>
        <a href="{% url 'register' %}?continue={{ request.get_full_path }}" class="sub-menu-link">
          <img src="{% static '/img/setting.png' %}" alt="">
          <p>Register</p>
          <span>></span>
        </a>
        {% endif %}

      </div>
    </div>

  </header>

  {% block content %}
   
  {% endblock %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="{% static 'js/restaurant.js' %}"></script>
  <script src="{% static 'js/edit.js' %}"></script>
</body>
</html>